export enum GameGenres {
  ACTION = "Action",
  INDIE = "Indie",
  ADVENTURE = "Adventure",
  RPG = "RPG",
  STRATEGY = "Strategy",
  SHOOTER = "Shooter",
  CASUAL = "Casual",
  SIMULATION = "Simulation",
  PUZZLE = "Puzzle",
  ARCADE = "Arcade",
  PLATFORMER = "Platformer",
  RACING = "Racing",
  MASSIVELY_MULTIPLAYER = "Massively Multiplayer",
  SPORTS = "Sports",
  FIGHTING = "Fighting",
  FAMILY = "Family",
  BOARD_GAMES = "Board Games",
  EDUCATIONAL = "Educational",
  CARD = "Card"
}
